logging:
  level:
    org.apache.activemq.artemis.jms.bridge: INFO

spring:
  ssl:
    bundle:
      jks:
        mqssl:
          truststore:
            location: "file:truststore/clientkey.jks"
            password: changeit
